# Generated by Django 4.0.4 on 2022-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('crm', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'medicos',
                'managed': True,
            },
        ),
    ]
