# Generated by Django 4.0.4 on 2022-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicos',
            old_name='id_medico',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='medicos',
            name='crm',
            field=models.CharField(max_length=4),
        ),
    ]
