# Generated by Django 4.0.4 on 2022-04-19 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0002_rename_id_medico_medicos_id_alter_medicos_crm'),
        ('agendas', '0002_alter_agendas_options_agendas_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.datetime.now)),
                ('horario', models.TimeField(choices=[(datetime.time(8, 0), '8:00:00'), (datetime.time(8, 30), '8:30:00'), (datetime.time(9, 0), '9:00:00'), (datetime.time(9, 30), '9:30:00'), (datetime.time(10, 0), '10:00:00')], default=datetime.time(8, 0))),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='agendas.agendas')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medicos.medicos')),
            ],
            options={
                'db_table': 'consultas',
                'managed': True,
                'unique_together': {('dia', 'horario', 'medico')},
            },
        ),
    ]
