# Generated by Django 4.0.4 on 2022-04-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultas',
            options={'managed': True, 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
