# Generated by Django 4.0.4 on 2022-04-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consultas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultas',
            options={'managed': True},
        ),
    ]
