# Generated by Django 4.0.4 on 2022-04-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_alter_agendas_options_alter_registrohorarios_options'),
        ('consultas', '0003_alter_consultas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.registrohorarios'),
        ),
    ]
