# Generated by Django 4.0.4 on 2022-04-19 20:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_rename_id_medico_medicos_id_alter_medicos_crm'),
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendas',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='agendas',
            name='horario',
            field=models.TimeField(choices=[(datetime.time(8, 0), '8:00:00'), (datetime.time(8, 30), '8:30:00'), (datetime.time(9, 0), '9:00:00'), (datetime.time(9, 30), '9:30:00'), (datetime.time(10, 0), '10:00:00')], default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='agendas',
            name='dia',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='agendas',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='medicos.medicos'),
        ),
        migrations.AlterUniqueTogether(
            name='agendas',
            unique_together={('dia', 'horario', 'medico')},
        ),
        migrations.AlterModelTable(
            name='agendas',
            table='agendas',
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
