# Generated by Django 4.0.4 on 2022-04-20 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_medicos_options_alter_medicos_crm_and_more'),
        ('agendas', '0002_alter_agendas_options_agendas_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='agendas',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='agendas',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendas',
            name='inserido_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendas',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agendas',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
        ),
        migrations.AlterUniqueTogether(
            name='agendas',
            unique_together={('medico', 'dia')},
        ),
        migrations.AlterModelTable(
            name='agendas',
            table=None,
        ),
        migrations.RemoveField(
            model_name='agendas',
            name='horario',
        ),
        migrations.AddField(
            model_name='agendas',
            name='agendas',
            field=models.ManyToManyField(to='agendas.registrohorarios'),
        ),
    ]
