# Generated by Django 4.0.4 on 2022-04-18 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_alter_agendas_options_agendas_horarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='dia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='agendas',
            name='horarios',
            field=models.CharField(max_length=200),
        ),
    ]
