# Generated by Django 4.0.4 on 2022-04-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_registrohorarios_alter_agendas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendas',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterModelOptions(
            name='registrohorarios',
            options={'verbose_name': 'Registro de Horario', 'verbose_name_plural': 'Registros de Horarios'},
        ),
    ]
