# Generated by Django 4.0.4 on 2022-04-18 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_alter_agendas_dia_alter_agendas_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='horarios',
            field=models.TimeField(choices=[(datetime.time(8, 0), '8:00'), (datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00')]),
        ),
    ]
