# Generated by Django 4.0.4 on 2022-04-18 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0006_remove_agendas_horarios_agendas_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='dia',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
