# Generated by Django 4.0.4 on 2022-04-18 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0008_alter_agendas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='dia',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
