# Generated by Django 4.0.4 on 2022-04-18 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0010_alter_agendas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='agendas',
            name='dia',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
