# Generated by Django 4.0.4 on 2022-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0014_alter_agendas_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='dia',
            field=models.DateField(),
        ),
    ]
