# Generated by Django 4.0.4 on 2022-04-18 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_rename_id_medico_medicos_id_alter_medicos_crm'),
        ('agendas', '0016_alter_agendas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='medicos.medicos'),
        ),
    ]
